name: Hourly Sensor Data Simulation

on:
  schedule:
    - cron: "0 * * * *"   # cada hora
  workflow_dispatch:      # para ejecutarlo manualmente

jobs:
  insert-fake-data:
    runs-on: ubuntu-latest

    steps:
      - name: Insert fake sensor telemetry
        run: |
          curl -i \
            -H "Authorization: Bearer ${{ secrets.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvY2phZXJiZGpzbXF2d212a3VkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MzY2MTY0NCwiZXhwIjoyMDc5MjM3NjQ0fQ.HKt6baX9nFGsV38DKrk4FAoxNZkunzRKvLLpmtU7cdE}}" \
            -H "Content-Type: application/json" \
            -X POST \
            -d '{}' \
            https://vocjaerbdjsmqvwmvkud.supabase.co/functions/v1/insert-sensor-data
